### ISSUE TITLE
Menambahkan Tautan Demo Aplikasi dan Format Penulisan Templat HTML

### ISSUE THREAD

**Issue by jefrydco** [Rakhmadi/CodeHighlighter#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Rakhmadi. Mas juga sudah menambahkan beberapa gaya sendiri dan menggunakan Bootstrap sebagai kerangka kerja.

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

1. Menambahkan Tautan ke Demo Aplikasi
Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Tautan ke demo aplikasi akan sangat berguna bagi teman-teman yang ingin melihat hasil proyek Mas ini tanpa harus menjalankannya di lokal.

2. Format Penulisan Templat HTML
https://github.com/Rakhmadi/CodeHighlighter/blob/96cb9aa31c386fb8277f2ef42e43b021ec83d070/src/App.vue#L69-L85

Pada bagian tersebut sepertinya kodenya kurang terformat denagn baik Mas, biasanya hal tersebut dikarenakan format otomatis dari eslint. Mungkin Mas bisa memformatnya secara manual atau bisa juga menggunakan HTML Beautifier seperti [Code Beautify](https://codebeautify.org/htmlviewer/).

Semangat selalu ya! :muscle:

**Comment by Rakhmadi** [comment]
terima kasih saran nya
